postgresql:
  image: postgres:9.5
  ports:
    - '5432'
  volumes:
    - postgresql:/var/lib/postgresql/data

redis:
  image: redis:3.0.5
  ports:
    - '6379'
  volumes:
    - redis:/var/lib/redis/data

memcached:
  image: memcached:1.4.31
  ports:
    - '11211'

elasticsearch:
  image: elasticsearch:5
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - '9200'
    - '9300'

web: &app_base
  build: .
  env_file: .env
  environment:
    RAILS_ENV: production
  links:
    - elasticsearch
    - postgresql
    - memcached
    - redis
  command: bundle exec puma -C config/puma.rb
  ports:
    - "7000"

worker:
  <<: *app_base
  ports: []
  command: bundle exec sidekiq -C config/sidekiq.yml
