postgresql:
  image: postgres:9.5
  ports:
    - '5432'
  volumes:
    - ./data/postgresql:/var/lib/postgresql/data

redis:
  image: redis:3.0.5
  ports:
    - '6379'
  volumes:
    - ./data/redis:/data

memcached:
  image: memcached:1.4.31
  ports:
    - '11211'

elasticsearch:
  image: elasticsearch:2.4.1
  volumes:
    - ./data/elasticsearch:/usr/share/elasticsearch/data
  ports:
    - '9200'
    - '9300'

web:
  build: .
  links:
    - app
    - worker
  command: nginx -c /etc/nginx/nginx.conf
  volumes:
    - ./shared/ssl:/var/www/ssl
    - ./log:/var/www/log
    - ./shared/cache/assets:/var/www/homeland/public/assets
    - ./shared/system:/var/www/homeland/public/system
  ports:
    - "80:80"
    - "443:443"

app: &app_base
  build: .
  env_file: app.env
  links:
    - elasticsearch
    - postgresql
    - memcached
    - redis
  volumes:
    - ./shared/cache/assets:/var/www/homeland/public/assets
    - ./shared/system:/var/www/homeland/public/system
    - ./log:/var/www/homeland/log
    - ./tmp:/var/www/homeland/tmp
  command: bundle exec puma -C config/puma.rb
  ports:
    - "7000"

worker:
  <<: *app_base
  ports: []
  command: bundle exec sidekiq -C config/sidekiq.yml -L /var/www/log/sidekiq.log
