production:
  adapter: postgresql
  encoding: utf-8
  database: homeland
  username: postgres
  password:
  host: postgresql
  pool: 64

development:
  adapter: postgresql
  encoding: utf-8
  database: homeland-dev
  pool: 64

test: &test
  adapter: postgresql
  encoding: utf-8
  database: homeland-test
  pool: 64